name: StaticPub build
# Run Workflow when
on:
  # Pushes changes and these are modified
  push:
    branches: ['main']
    paths: ['staticpub.py', '*.cfg', '_entries/*', '_media/*']
  # Or manually
  workflow_dispatch:
# Just one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
# And a single job that...
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkouts code
    - name: "checkout repo content"
      uses: actions/checkout@v2
    # Setups python 3.10
    - name: "setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    # Runs StaticPub
    - name: Run StaticPub
      run: python staticpub.py
    # and commits changes if something's new
    - name: Commit files
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git add .
        git commit -m "update -> $(date)"
    # Finally pushing the changes
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
